import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server";

// @ts-ignore - the server build file is generated by `remix vite:build`
const remixHandler = createPagesFunctionHandler({ build });

export const onRequest: typeof remixHandler = async (context) => {
  const url = new URL(context.request.url);
  if (url.hostname.startsWith("www.")) {
    url.hostname = url.hostname.slice(4);
    return Response.redirect(url.toString(), 301);
  }
  return remixHandler(context);
};
