import {
  FolderOpen,
  Backpack,
  Bike,
  Cookie,
  Drumstick,
  Film,
  FlaskConical,
  Globe,
  Grid3x3,
  Medal,
  PiggyBank,
  Sandwich,
  Star,
  UtensilsCrossed,
  Beer,
  Book,
  BookOpen,
  Briefcase,
  Cake,
  Dices,
  Droplets,
  Heart,
  House,
  Music,
  PartyPopper,
  Popcorn,
  Presentation,
  School,
  Soup,
  Tent,
  Trophy,
  Utensils,
  Wine,
  type LucideIcon,
} from "lucide-react";
import type { TemplateIcon as TemplateIconKey } from "~/utils/templates";

const ICONS: Record<TemplateIconKey, LucideIcon> = {
  heart: Heart,
  book: Book,
  school: School,
  utensils: Utensils,
  party: PartyPopper,
  cake: Cake,
  popcorn: Popcorn,
  droplets: Droplets,
  soup: Soup,
  briefcase: Briefcase,
  "book-open": BookOpen,
  trophy: Trophy,
  dice: Dices,
  wine: Wine,
  beer: Beer,
  presentation: Presentation,
  house: House,
  tent: Tent,
  music: Music,
  sandwich: Sandwich,
  backpack: Backpack,
  film: Film,
  bike: Bike,
  globe: Globe,
  drumstick: Drumstick,
  star: Star,
  flask: FlaskConical,
  cookie: Cookie,
  bingo: Grid3x3,
  medal: Medal,
  "piggy-bank": PiggyBank,
  restaurant: UtensilsCrossed,
  folder: FolderOpen,
};

export default function TemplateIcon({ icon, className }: { icon: TemplateIconKey; className?: string }) {
  const Icon = ICONS[icon];
  return <Icon className={className} aria-hidden="true" />;
}
